cabal-version:      3.4
name:               zadanie3
version:            0.1.0.0
build-type:         Simple

common warnings
    ghc-options: -Wall

executable zadanie3
    main-is:          Main.hs

    other-modules:    Types,
                      Parser,
                      Evaluator

    build-depends:    base >= 4.15.1.0,
                      haskell-src,
                      containers

    hs-source-dirs:   app

    default-language: GHC2021
    
    -- Author: Aliaksei Papkouski, MIM UW 
